Import('RTT_ROOT')
Import('rtconfig')
import rtconfig
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = []


if GetDepend('LCKFB_3_5_COLOR_SCREEN') and GetDepend('USING_LCKFB_TRANSPLANT_CODE'):
    src = Glob(os.path.join(cwd, '*.c'))

group = DefineGroup('lckfb-3-5-color-screen', src, depend = [''], CPPPATH = CPPPATH)

Return('group')